### ISSUE TITLE
Tool icons are not shown

### ISSUE THREAD

**Issue by probonopd** [flameshotapp/packages#1]
Most likely they are tried to be loaded from somewhere in `/usr/` whereas a relative path (e.g., constructed from http://doc.qt.io/qt-5/qcoreapplication.html#applicationDirPath) should be used so that the resources are loaded from a location relative to the main executable.

**Comment by holazt** [comment]
@probonopd Are you talking about AppImage? Please tell me your OS information and desktop environment.

**Comment by probonopd** [comment]
Yes, AppImage. https://transfer.sh/jHlXc/flameshot_0.6.0_x86_64.appimage on `xubuntu-18.04-desktop-amd64.iso` and other systems.

**Comment by holazt** [comment]
This issue cannot be reproduced in fedora 29 Gnome.

**Comment by tuxflo** [comment]
Still valid in KDE Neon (based on Ubuntu 18.04).
