### ISSUE TITLE
not flatpak package yet?

### ISSUE THREAD

**Issue by Lvaskz** [flameshotapp/packages#12]
See title above

**Comment by holazt** [comment]
@Lvaskz Yes, flatpak package need helps.

**Comment by zendre4** [comment]
What is the problem with the flatpak apps ? Maybe I can help ...

**Comment by holazt** [comment]
@zendre4  Fork from https://github.com/flathub/flathub, here it is https://github.com/flameshotapp/flathub/tree/org.dharkael.Flameshot

**Comment by zendre4** [comment]
@ZetaoYang Ok I will try to fork it and buile  ... But they have not a bug lists ?

**Comment by ZetaoYang** [comment]
@zendre4 The pull request: https://github.com/flathub/flathub/pull/865

**Comment by holazt** [comment]
Resolved at PR https://github.com/flameshot-org/flameshot/pull/866
