### ISSUE TITLE
flatpak packaging CI needs help

### ISSUE THREAD

**Issue by holazt** [flameshotapp/packages#2]

**Comment by Alexander-Wilms** [comment]
I don't have any experience with CI, bitte I can try. What needs to be done? Why so you have seperaten folders Form KDE, Gnome and Freedesktop?

Just for reference, here's how the SuperTux Flatpak CI works: https://gitlab.com/SuperTux/flatpak/blob/master/.gitlab-ci.yml

**Comment by holazt** [comment]
https://travis-ci.org/flameshotapp/packages/jobs/473490360
CI building flatpak error, but on my local machine, it was  packaged normally.
I just do a test for different run-times, now I focus on kde.

**Comment by holazt** [comment]
Those Dockerfile is unuseful. I will remove them.

**Comment by jeteokeeffe** [comment]
Hi, I'd like to help. I'm getting errors with running your flatpak manifest. When I remove the post processing, I'm getting a successful build.

I created my own test, https://github.com/jeteokeeffe/flameshot-flatpak

**Comment by holazt** [comment]
@jeteokeeffe Thank you, I noticed that `post-install` is useless, because `qmake` will solve it.

**Comment by jeteokeeffe** [comment]
@ZetaoYang Let me know if you need anything else ...

**Comment by holazt** [comment]
@jeteokeeffe Thank you, I need to build flatpak packages to publish.

**Comment by jeteokeeffe** [comment]
@ZetaoYang If you go the flathub route, you just need to do 6 steps (fork, commit then pull request) and they'll build it for you. You'll have write access to change your manifest file. I recommend it vs hosting your own site/packages.

https://github.com/flathub/flathub/wiki/App-Submission#how-to-submit-an-app

**Comment by holazt** [comment]
@jeteokeeffe I will accept your advice. Thank you.

**Comment by holazt** [comment]
@jeteokeeffe https://github.com/flathub/flathub/pull/865

**Comment by jeteokeeffe** [comment]
You're almost there! I'm pretty sure you need to an appdata.xml (eg. org.dharkael.Flameshot.appdata.xml) file in your repo so the build process for x86_64 will work. See the example below of how it should look. Also, you need to make sure you have icon pngs for 128x128 and 64x64 (See https://github.com/flathub/flathub/wiki/App-Requirements#application-icons).


Example of appdata.xml file
https://github.com/flatpak/qt-flatpak-demo/blob/master/org.flatpak.qtdemo.appdata.xml

**Comment by holazt** [comment]
flameshot flatpak will be at flathub. So I closed.

**Comment by jeteokeeffe** [comment]
Awesome, Thank You!

**Comment by zendre4** [comment]
In this day the app was not publish, because flathub need changes : 

https://github.com/flathub/flathub/pull/865

When did you plan to correct it ?
