### ISSUE TITLE
How do you install the snap package?

### ISSUE THREAD

**Issue by AsaAyers** [flameshotapp/packages#4]
My work computer is on 18.04, so `sudo apt install flameshot` gives me a version that does't have text annotation. I was hoping to try the snap version to see if it's been updated, and I'm already using some other snap packages. But the readme here doesn't provide any instructions, and I can't find this published anywhere else.

```
asa:~/Downloads$ snap install flameshot
error: snap "flameshot" not found
asa:~/Downloads$ snap search flameshot
No matching snaps for "flameshot"
```

It's not here https://snapcraft.io/search?category=&q=flameshot

**Comment by ZetaoYang** [comment]
@AsaAyers The new snap build: https://transfer.sh/VIwah/flameshot_0.6.0_amd64.snap (Files stored for 14 days)

**Comment by holazt** [comment]
@AsaAyers Release! https://snapcraft.io/flameshot-app

**Comment by AsaAyers** [comment]
Thanks. I uninstalled the version from apt and installed the snap, but I'm having trouble getting it to work.

```
asa:~$ flameshot-app.flameshot
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
^C
```

Is the binary actually supposed to be named `flameshot-app.flameshot`? I thought snap packages were supposed to be self-contained or install their dependencies. It also seems like I have the dependencies, so I'm not sure why it's not being found.

```
asa:~$ apt search canberra-gtk-module
Sorting... Done
Full Text Search... Done
libcanberra-gtk-module/bionic,now 0.30-5ubuntu1 amd64 [installed,automatic]
  translates GTK+ widgets signals to event sounds
```

```
asa:~$ apt search atk-bridge
Sorting... Done
Full Text Search... Done
libatk-bridge2.0-0/bionic,now 2.26.2-1 amd64 [installed,automatic]
  AT-SPI 2 toolkit bridge - shared library

libatk-bridge2.0-dev/bionic,now 2.26.2-1 amd64 [installed,automatic]
  Development files for the AT-SPI 2 toolkit bridge
...snip...
```

```

asa:~$ apt search gail
Sorting... Done
Full Text Search... Done
...snip...
libabigail0/bionic 1.2-1 amd64
  ABI Generic Analysis and Instrumentation Library (runtime)

libgail-3-0/bionic,now 3.22.30-1ubuntu1 amd64 [installed,automatic]
  GNOME Accessibility Implementation Library -- shared libraries

...snip...
libgail-common/bionic,now 2.24.32-1ubuntu1 amd64 [installed]
  GNOME Accessibility Implementation Library -- common modules

libgail-dev/bionic 2.24.32-1ubuntu1 amd64
  GNOME Accessibility Implementation Library -- development files

libgail-doc/bionic,bionic 2.24.32-1ubuntu1 all
  documentation files of the Gail library

libgail18/bionic,now 2.24.32-1ubuntu1 amd64 [installed,automatic]
  GNOME Accessibility Implementation Library -- shared libraries
```

```
asa:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Pop!_OS 18.04 LTS"
```

I can run flameshot 0.5.1-2 that I can install with `apt`, but my goal is to run a new enough version to be able to annotate my screenshots with text. I used to use Shutter, but it seems to be unmaintained, so I'm in search of a new screenshot tool. So far I'm very impressed with flameshot. I have a 2nd computer running 18.10 that does have text annotation and pinning.

**Comment by holazt** [comment]
@AsaAyers The name "flameshot"  was already occupied on snapcraft store. so I choose "flameshot-app".

**Comment by holazt** [comment]
@AsaAyers try https://github.com/lupoDharkael/flameshot#installation,  [opensuse software repository](https://software.opensuse.org//download.html?project=home%3AVitzy&package=flameshot).
flameshot v0.6.0 contains text feature.
flameshot release log: https://flameshot.js.org/#/changelog

**Comment by holazt** [comment]
release new snap build package.

**Comment by hmvs** [comment]
Tried both: 
latest/stable | v0.6.0+git37.8887b4e 
latest/edge | v0.6.0+git70.91ba28c

Both failing with: 

```
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported

```


Ubuntu 18.04
Installed from Snap store:
`snap install flameshot-app`

**Comment by holazt** [comment]
@hmvs Try new release https://github.com/flameshotapp/packages/releases

**Comment by hmvs** [comment]
Thanks. 
@ZetaoYang can you push it to snap store?
