### ISSUE TITLE
Flameshot Desktop File Missing Exec Field

### ISSUE THREAD

**Issue by TheMightyDuder** [flameshotapp/packages#7]
After installing Flameshot via Snap on Ubuntu 18.04 LTS I found that the Flameshot desktop file (/var/lib/snapd/desktop/applications/flameshot-app_flameshot.desktop) is missing the EXEC field. 

When a user tries to launch Flameshot from the menu icon they will get the following error: 

> Failed to launch “Flameshot”: Desktop file didn’t specify Exec field

This requires the user to modify the .desktop file and add the following line: 

> Exec=flameshot-app.flameshot

This will allow the user to launch Flameshot from the menu icon. Otherwise they will need to launch the application through the CLI.

**Comment by holazt** [comment]
So sorry. I'm very busy on recent days, this weekend I will solve this problem.

**Comment by TheMightyDuder** [comment]
No worries, I was able to correct the issue on my install(s) - tested on a couple different Ubuntu 18.04 installs to make sure it was a reproducible issue before I reported it. Just wanted to relay my findings and post so if anyone came across it they know how to fix until it was patched. Thanks for all the hardwork!

**Comment by hurricanehrndz** [comment]
@ZetaoYang and @TheMightyDuder 

The description of the error is actually incorrect. The issue stems from snapcraft now requiring  a specific syntax for desktop files. I will formulate a pull request that should address the issue soon.

https://snapcraft.io/docs/snap-format

Read Desktop-Files

**Comment by hurricanehrndz** [comment]
@ZetaoYang 

My fork now includes all necessary fixes to close several issues. Everything is in my fork commit history. 

Sample snap for testing is here:
https://transfer.sh/evLHr/flameshot-app_v0.6.0-git63.19d7010_amd64.snap

**Comment by hurricanehrndz** [comment]
I would have submitted a pull request, but was not able at the time

**Comment by hurricanehrndz** [comment]
Here is comparison of new vs old. 
![flameshot-core18](https://user-images.githubusercontent.com/5804237/64144046-0dcde600-cdd0-11e9-8cc6-f5ce2e7b6d45.png)
![flameshot-current](https://user-images.githubusercontent.com/5804237/64144048-10304000-cdd0-11e9-80ad-d80c03864bf2.png)

**Comment by holazt** [comment]
@hurricanehrndz I will check your fork later. Thanks again.

**Comment by hurricanehrndz** [comment]
@ZetaoYang 

Thanks, I would have submitted a pull request, but github is seriously doing some weird stuff right now.
