### ISSUE TITLE
Tools icon not showing up.

### ISSUE THREAD

**Issue by abspython** [flameshotapp/packages#8]
The App-image of flameshot is executed successfully. But when a screenshot is taken by clicking the tray icon and dragging a box, the tools icon are not showing up. Need a solution.
Distro : Debian Stretch
Desktop Environment : i3wm
Similar Issue as #1

**Comment by Nanco300** [comment]
The same error in KDE Plasma.

**Comment by Lvaskz** [comment]
same issue with linuxmint  19.2 cinnamon 64 bit

**Comment by zicklag** [comment]
This might have something to do with: https://github.com/lupoDharkael/flameshot/issues/535. It looks like there might be an undeclared dependency on `libqt5svg5` or something.

**Comment by holazt** [comment]
I think this PR https://github.com/flameshot-org/flameshot/pull/866 should include `libqt5svg5-dev`

**Comment by holazt** [comment]
I closed this issue. If you are running a new appimage(built from core repository https://github.com/flameshot-org/flameshot) and still have problems, please submit an issue in the core repository https://github.com/flameshot-org/flameshot.
